### ISSUE TITLE
Semaine 3 : TODO pour CD il faut mémoriser le répertoire courant

### ISSUE THREAD

**Issue by seintur** [MaximeDSM/CARTP1#4]

**Comment by MaximeDSM** [comment]
Bonjour monsieur, quand on utilise CD sans argument depuis le client FTP, le client oblige de préciser un argument donc côté serveur on ne peut pas avoir la commande CWD seule comme on pourrait faire sur un terminale, quel est le but de mémoriser le répertoire courant ?

**Comment by seintur** [comment]
Savoir quel est le répertoire courant dans lequel se trouve la session de l'utilisateur. Il s'agit du même comportement que lorsque l'on utilise cd dans un terminal Unix, Windows, macOS.

**Comment by MaximeDSM** [comment]
D'accord, merci monsieur, le problème est réglé.
